spring.application.name=LoanManagement

spring.datasource.url=jdbc:postgresql://localhost:5432/abesdb2
spring.datasource.username=postgres
spring.datasource.password=1111

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true